### PR TITLE
Add support for callHackageDirect

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by expipiplus1** [comment]
what is this? `error: path '/nix/store/llpzh1xzimwlr2byxmyzz1nm5l0q3rxn-nixexprs.tar.xz' is not in the Nix store`

https://github.com/expipiplus1/update-nix-fetchgit/pull/41/checks?check_run_id=1338562438#step:10:487

**Comment by sorki** [comment]
Looks it tries to import `nixexprs` from `/nix/store` but we operate with temporary one so gets mismatch?

**Comment by expipiplus1** [comment]
Weird, why does it want to fetch that for `mirror://` urls? Is it to get the list of mirrors or something?

**Comment by expipiplus1** [comment]
I'll disable this check for now, we can enable it at a later date

**Pull request merged**
