### PR TITLE
Convert shell testsuite to Haskell one with tasty-golden

### PR DESCRIPTION
**Pull request by sorki**
Doesn't work in Nix sandbox.

Will leave this here as a TODO for me to either
- fix sandbox to allow creating `/nix`
- build native Haskell fetchers

### CODE REVIEW

**Comment by expipiplus1** [comment]
>     * fix sandbox to allow creating `/nix`

Sounds like a job for recursive-nix (which doesn't exist :/)

Thanks for doing this! Would repo write permissions be useful?

Perhaps running the tests in a nixos container would work?

**Comment by sorki** [comment]
> > ```
> > * fix sandbox to allow creating `/nix`
> > ```
> 
> Sounds like a job for recursive-nix (which doesn't exist :/)

I think it does now as an experimental feature but that's not what we want I think as it interacts with hosts store? Not sure..

> 
> Thanks for doing this! Would repo write permissions be useful?

You mean for CI so the copy-outfile-back works?

> 
> Perhaps running the tests in a nixos container would work?

It would but that isn't that appealing to me - the reason I wanted this is so the tests are run by Hydra and `nix build` via standard Haskell infra but still - not that important in this case, more like nice to have so you don't need to run shell script - just `cabal test`.

CI seems to struggle with `tasty-discover` as well, weird.

**Comment by expipiplus1** [comment]
> I think it does now as an experimental feature but that's not what we want I think as it interacts with hosts store? Not sure..

Yeah, you're right, polluting the store isn't very nice.

> > Thanks for doing this! Would repo write permissions be useful?
> 
> You mean for CI so the copy-outfile-back works?

I mean so you can merge your changes and all that, you probably know the code better than I do at this point :)

> > Perhaps running the tests in a nixos container would work?
> 
> It would but that isn't that appealing to me - the reason I wanted this is so the tests are run by Hydra and `nix build` via standard Haskell infra but still - not that important in this case, more like nice to have so you don't need to run shell script - just `cabal test`.

Hmm, how does Hydra perform the nixos tests?

**Comment by sorki** [comment]
> > I think it does now as an experimental feature but that's not what we want I think as it interacts with hosts store? Not sure..
> 
> Yeah, you're right, polluting the store isn't very nice.
> 
> > > Thanks for doing this! Would repo write permissions be useful?
> > 
> > 
> > You mean for CI so the copy-outfile-back works?
> 
> I mean so you can merge your changes and all that, you probably know the code better than I do at this point :)

Ah :) I don't mind the invite, increasing the bus factor is good for sure so I can fix this if you can't for some reason. I would still go through the PR process so you (and the CI) can take a look.

Ideally I would love to see projects like these hosted under `haskell-nix` organization but first we need to figure out the org permissions before even considering that.

> 
> > > Perhaps running the tests in a nixos container would work?
> > 
> > 
> > It would but that isn't that appealing to me - the reason I wanted this is so the tests are run by Hydra and `nix build` via standard Haskell infra but still - not that important in this case, more like nice to have so you don't need to run shell script - just `cabal test`.
> 
> Hmm, how does Hydra perform the nixos tests?

These are run via qemu/kvm VMs which would work for this but I would prefer less heavy-weight solution (if I can come up with one).

**Comment by expipiplus1** [comment]
> Ah :) I don't mind the invite, increasing the bus factor is good for sure so I can fix this if you can't for some reason. I would still go through the PR process so you (and the CI) can take a look.

Invited as a collaborator :)

> 
> Ideally I would love to see projects like these hosted under `haskell-nix` organization but first we need to figure out the org permissions before even considering that.
> 

Yeah, that'd be good. Might need to give the code a once-over first :)

**Comment by sorki** [comment]
Accepted, thanks! Do you want me to handle tagging and uploading the package to Hackage as well? If so you can add me as maintainer - my profile https://hackage.haskell.org/user/srk

**Comment by expipiplus1** [comment]
That would be very kind! I'll add you

**Comment by sorki** [comment]
Tagged the two releases and published a new one on Hackage:

```
* 8892c8f (tag: 0.1.1.0) Release 0.1.1.0
* 480f75c (tag: 0.1.0.0) Relax upper bound on transformers
```

Regarding this PR I'll take a look if I can make it work with the CI and we can possibly switch to it then and use `dontCheck` in `nixpkgs`.

**Comment by expipiplus1** [comment]
It would be great to get this merged!

**Comment by expipiplus1** [comment]
For the writing to /nix, could use a chroot, or could perhaps use a different NIX_STORE. How does nix itself run tests?

**Comment by sorki** [comment]
Thanks, didn't occur to me for some reason even though I'm already doing similar in `hnix-store`.. Managed to hit like 3 bugs while doing this - e6737ef is particularly unfortunate.

And one more with `tasty-discover` installed but not discovered by cabal /o\.

**Comment by sorki** [comment]
Fixed tasty-discover issue but now it requires Nix (nix-store) and nix-prefetch-git in PATH.

**Comment by sorki** [comment]
It fails on Ubuntus but Nix build looks good. How about disabling tests for cabal builds or even cabal builds itself? Different ghcs can be tried with Nix as well.

Another option would be to put IO testsuite behind a flag.

**Comment by expipiplus1** [comment]
Does it run on ubuntu if you use     `- uses: cachix/install-nix-action@v8`?

**Comment by expipiplus1** [comment]
\o/

**Comment by expipiplus1** [comment]
I've merged this branch with my `joe-several-changes` branch. If you wouldn't mind not force-pushing that would be super :)

**Comment by expipiplus1** [comment]
my merge here: https://github.com/expipiplus1/update-nix-fetchgit/pull/39/commits/a83862582ba3df51c461771355ba1f716428b1b0

Moved test exe desc to package.yaml and integrated my additional tests.

**Comment by sorki** [comment]
Cool. I've added last piece via 3dabb12baab4549548dd585273026ab930857fa0

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
https://github.com/NixOS/nix/issues/2919 might be useful perhaps

**Pull request closed without merging**
