### PR TITLE
add a longer package description from README

### PR DESCRIPTION
**Pull request by jpierre03**
Hackage page show current description "Please see README.md" and is not informative https://hackage.haskell.org/package/update-nix-fetchgit.

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thanks for the PR!

Personally, I'm not a huge fan of using cabal's description field, it just leads to duplication between the description and the readme. Hopefully some day soon Hackage will do something more sensible by default.

@DavidEGrayson Do you have any feelings on this?

**Comment by DavidEGrayson** [comment]
Hackage has a link to the [project's home page](https://github.com/expipiplus1/update-nix-fetchgit#readme) and that should be the main place where people get information about the project.  But I think a few sentences in the description field would be good too, so that people on the [Hackage page](https://hackage.haskell.org/package/update-nix-fetchgit-0.1.0.0) can quickly understand what it's about.  I probably would put less information in the description than is done in this PR, and in particular I wouldn't put the full list of function calls that get updated because that will probably be outdated at some point.

**Comment by DavidEGrayson** [comment]
Overall, this PR is an improvement so I would say to accept it and then edit it later if you want.

**Comment by expipiplus1** [comment]
In that case, I'd be happy to merge if the specific list of functions is removed.

**Comment by jpierre03** [comment]
@expipiplus1 Package description is shorter and doesn't mention functions anymore

**Comment by expipiplus1** [comment]
@jpierre03 did you mean to close this? I'm happy to merge.

**Comment by jpierre03** [comment]
@expipiplus1 nope, I did the modification and somehow pressed the wrong button.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
