### PR TITLE
Nixpkgs unstable

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
Oh, you made a pull request to yourself.  I thought it was a pull request to me for a moment there.

Thanks for working on this!   Getting this program to work with the latest nixpkgs unstable was going to be my next task.

However, I don't think that our release.nix file should be hard-coding a particular revision of the nixpkgs repository.  I think this program should be cross-platform, meaning that it works with many different versions of its dependencies and with many different versions of nixpkgs.  I think a good default would be to just run `import <nixpkgs> {}` and when we want to test building against specific versions of nixpkgs, we can use the NIX_PATH environment variable and/or set up a separate file that passes a different `pkgs` object to release.nix.

Actually, why is it even called release.nix?  Maybe it should just be build.nix?  Is there some standard for what nix files should exist for an application's source repository?  Who uses `src` argument to release.nix?

**Comment by expipiplus1** [comment]
I've seen release.nix before for this job (build instructions for hydra).

I quite like pinning things to a particular version of nixpkgs, it ensures that it'll keep working. Not doing so is like using dependencies without version bounds.

It would certainly be possible to have a `pkgs` argument to release.nix which defaults to a known working version.

Hydra uses the `src` argument.

**Comment by DavidEGrayson** [comment]
Assuming that the NixOS people use our release.nix file to build the package for this utility, I see some problems with that pinning:
- The package won't automatically get security fixes from its dependencies.  For instance, the `fetchFromGitHub` function we use probably relies on OpenSSL, a library known to have serious security vulnerabilities revealed on a regular basis.  Most old versions of OpenSSL are dangerous to use.
- The package won't automatically get bug fixes and improvements from its dependencies.  Like, if someone fixes a bug in the Haskell compiler that allows it to work on a new version of Mac OS X or some other new operating system, we won't get that automatically, and people will have to do extra work in order to get our program running on that system.
- If all the executable applications did this, there would be a huge explosion in the number of versions of GCC and GHC that must be compiled in order to build a complete system.  It's more efficient if you can just build one GCC, use that to build one GHC, and then use that GHC to build every Haskell program.  (Programs that really need an old GHC should be an exception to the rule, and the maintainers of those programs should try to fix them.)

I'm pretty new to the Nix world but I suspect that pinning expressions to a particular version of nixpkgs like this is not standard practice unless you are just writing a Nix expression for yourself to use.  If you're writing something for yourself to run on your own servers then it would seem fine.

**Comment by expipiplus1** [comment]
There will be many GCCs and GHCs on a system if one always tracks the latest version of nixpkgs. Pinning a version and tracking a version can both be sorted with a garbage collect.

There's nothing stopping the security conscience from using whatever version of nixpkgs they like to compile this. Sadly nixpkgs unstable doesn't differentiate between feature updates and security updates.

All the build inputs are hashed, so it'd have to be some pretty major vulnerability in openssl for the user to put themselves at risk using this. 

It's pretty annoying to download someone's project and have to fix bitrot.

Perhaps when nixpkgs-16.09 comes around we could use the head of that. I think that the benefits of doing this outweigh the downsides.

**Comment by DavidEGrayson** [comment]
> All the build inputs are hashed, so it'd have to be some pretty major vulnerability in openssl for the user to put themselves at risk using this.

It looks like there have been 5 high-severity [bugs in OpenSSL in 2016](https://www.openssl.org/news/vulnerabilities.html#y2016), and we're only 7 months into the year.

> There's nothing stopping the security conscious

It's true that people can modify the code and do whatever they want, so really the question here is what should the defaults be.  In particular, what behavior should we have when someone runs `nix-shell` because they want to develop the app, and how will the package be built when we submit it to nixpkgs as a pull request.  I think that in both of those cases, we ought to not choose defaults that subject our users to the three pitfalls I listed, especially the security issue.  (If we want to have an alternate building method that is pinned to a particular nixpkgs version but is not used by default, I wouldn't object.  It can help us debug things when they break.)

> It's pretty annoying to download someone's project and have to fix bitrot.

I'd like to try to understand this concern better.  What type of person would encounter bitrot in our project and have justifiable annoyance?  I'm just thinking that the people who want a stable environment will use nixpkgs-16.09 or whatever the latest release number is, and that release will have been tested by the nixpkgs developers and they will have already fixed all bit rot, especially for utilities like ours that will be popular and important for the Nix ecosystem.  The people who are using the nixpkgs-unstable channel are probably doing that because they want to use the latest versions of everything and they understand there will be some bit rot, but they accept that because (to them) the benefits outweigh the costs.  I guess you're mainly worried about the nixpkgs developers themselves who have the task of making everything build correctly?  I'm new to Nix so maybe I'm missing something.

**Comment by DavidEGrayson** [comment]
I think the nixpkgs people would reject this pinning because here is how @edolstra describes the Nixpkgs collection in his [thesis](http://grosskurth.ca/bib/2006/dolstra-thesis.pdf) (section 7.1):

> In general, we endeavour to standardise on a single version of a component within a given release of Nixpkgs, but this is not always possible. For instance, several versions of the GNU C Compiler are necessary because there is no single version of the compiler that can build all components.  Also, some library components have major revisions that are not backwards compatible (e.g., versions 1 and 2 of the GUI library GTK).

**Comment by expipiplus1** [comment]
Oh sure, I'm not intending this pinned version to make it into nixpkgs proper. This is purely for development. Sorry for the misunderstanding.

For haskell packages nixpkgs generates what's in default.nix automatically from the .cabal file.

**Comment by DavidEGrayson** [comment]
Cool.  I hope you'll also agree to my eventual pull request that will change default.nix and shell.nix to not use a pinned version of Nixpkgs.

In the mean time, I'm having a hard time verifying that your pull request actually lets the program build on nixpkgs-unstable.

Here is a shell session showing how I checked out the main commit of your pull request, but when I ran `nix-shell` it attempted to build GHC, and it failed because it couldn't build Glob, because it couldn't find semigroups 0.18.x.

```
$ git log -1
commit 1a62d35df9be78134b6973f3d2a76054eaa7bfef
Date:   Wed Aug 3 21:40:28 2016 +0100

    formatting

$ nix-shell
these derivations will be built:
  /nix/store/vapsjhfi9ay3lfwbicggaxa83bcxg06i-exceptions-0.8.2.1.drv
  /nix/store/fims0ih0lcvk5qa107zf8i5zbsf254hj-temporary-1.2.0.4.drv
  /nix/store/6pr9x67ga7cc633nkzqw1q1j803vq84f-silently-1.2.5.drv
  /nix/store/9iwmy7lpxpqdpv7viykfllsa5k0qldg5-hspec-meta-2.2.1.drv
  /nix/store/cw1gggksp7fxkq97park9amxqqphhi7h-hspec-discover-2.2.3.drv
  /nix/store/wdgm4cadn0m1ck7kqwc5vlbzzf69qkg7-hspec-core-2.2.3.drv
  /nix/store/z72mj9ihrp2prpxidl44gn8zmvq9cgwp-hspec-2.2.3.drv
  /nix/store/afy8v1aadi394mk7fn62fjd3pkps6sbl-stringbuilder-0.5.0.drv
  /nix/store/ki4qr351dplb6raq9amaxmpzn70am4hl-base-compat-0.9.1.drv
  /nix/store/zibrnra6lavl3gdz444ir7jwp9ln93vl-with-location-0.1.0.drv
  /nix/store/69zvhlq0x54q5smyia5gashdpiqavh8g-doctest-0.11.0.drv
  /nix/store/782gky7yjs2bj5avyvkfb9rgd4rmk69l-distributive-0.5.0.2.drv
  /nix/store/vqa66hd1k3kpnlsd1gp2ljnfa1lwpxc8-comonad-5.drv
  /nix/store/in1g8ypyzy2hq2wdcw3y5nji2njvghbm-bifunctors-5.3.drv
  /nix/store/80yzcnp4dqmmwwjirz6awn72n018vjsk-semigroupoids-5.1.drv
  /nix/store/0pp108nzxyhmaw0acr57ipk0xpjvmygd-reducers-3.12.1.drv
  /nix/store/24iv4ci3cdpkf6wkb83z4mnpkmfv7ich-generic-deriving-1.10.6.drv
  /nix/store/q2fxq6q3m2g6dk0pwx63ipi7izvnaw4g-tasty-ant-xml-1.0.2.drv
  /nix/store/sdk7sbvc0ifzckq8kl08q1x92bs4zxij-scientific-0.3.4.9.drv
  /nix/store/136a18bks3km8hqmnwa31jw41cxfyd12-attoparsec-0.13.0.2.drv
  /nix/store/2q9dj2zb9zf43lj0ybwbari2yvj9x5sx-profunctors-5.2.drv
  /nix/store/3aamgq6bvdf4zqc1xgscfmyjwzbn3r81-vector-th-unbox-0.2.1.6.drv
  /nix/store/4nw38gmfxp3wqwp88sgfkn2mhw0g9zqb-Glob-0.7.10.drv
  /nix/store/6lgsz3yyxna5d0va460vqmbxcyayc6bl-hastache-0.6.1.drv
  /nix/store/caqidn2z8y8v81awqdnn32p8ddckzfaj-erf-2.0.0.0.drv
  /nix/store/kxpklfqm6kf98nh54p45nq12gigb25g2-math-functions-0.2.0.1.drv
  /nix/store/ax0zki8y9w5n8j1qym3wkij3y7il5hcx-abstract-par-0.3.3.drv
  /nix/store/v95nyhrsd2v2qgq59ghihy2djv55zpx7-language-haskell-extract-0.2.4.drv
  /nix/store/n1i126chmdq3xx73m2scvj5n51yaxfb1-test-framework-th-0.2.4.drv
  /nix/store/plj2vfzxgnhgf1kzpvc007zkiiczp9w6-abstract-deque-0.3.drv
  /nix/store/zabs50adwdn5vjdvwpzwq6das5kfn3hc-monad-par-extras-0.3.3.drv
  /nix/store/l6mn1948vkwq8nfjpmmvbxxh5slmk8a2-monad-par-0.3.4.8.drv
  /nix/store/rgff0gp39rd3waxva3lsv9rqhxwhfsll-vector-binary-instances-0.2.3.2.drv
  /nix/store/xzbp49kx4k3hy737pihawf3yhlqngrpa-vector-algorithms-0.7.0.1.drv
  /nix/store/yq02xw1gp940d4jy9s7yqmbfs4lav3pm-aeson-0.11.2.0.drv
  /nix/store/asn02fv8kkdzzmjk68vvv2n5k6yy35kq-statistics-0.13.3.0.drv
  /nix/store/wsld7ljxbv72xykfdsv8hsx6dln5nj63-cassava-0.4.5.0.drv
  /nix/store/9wr5hy91csq2wprgrkynknyjvpf61pl8-criterion-1.1.1.0.drv
  /nix/store/600mxj5v4yd8rv99vw0plpq051hvhq93-charset-0.3.7.1.drv
  /nix/store/5pfn0ssgr15aakss198lbvq0jppg4c7p-free-4.12.4.drv
  /nix/store/pjf6c2qa248ffb97p45f2xnz0vhx44ap-adjunctions-4.3.drv
  /nix/store/ypjn7bwismhz0nl6if4nqii86k3h3g8d-kan-extensions-5.0.1.drv
  /nix/store/s53mv5p64crnil8c01lpp7qlz0dgmjlb-lens-4.14.drv
  /nix/store/zqpb793vdy3l6zkhdixqnmmad1hbraq2-parsers-0.12.4.drv
  /nix/store/f3a1k80l4wahpr4f3217gkl4jx929w3v-trifecta-1.6.drv
  /nix/store/3dgzb379kxyk6rfc6k9h9g5742d9j3pr-hnix-0.3.1.drv
  /nix/store/9iz89214q6gknan3ils61lhp9pvhf8z5-uniplate-1.6.12.drv
  /nix/store/4lplkhrvrnqxa5q3xirl15qipacxfzmd-ghc-7.10.3.drv
building path(s) ‘/nix/store/p19ggmfm45zaaqm7q124y0kzhpisq29j-Glob-0.7.10’
setupCompilerEnvironmentPhase
Build with /nix/store/0rdmqzy6ybv6ck5m4zpjzyfykn8s1ka4-ghc-7.10.3.
unpacking sources
unpacking source archive /nix/store/xfgybqri93gm1gm9jbgln8a24syvgw45-Glob-0.7.10.tar.gz
source root is Glob-0.7.10
setting SOURCE_DATE_EPOCH to timestamp 1468861139 of file Glob-0.7.10/tests/Utils.hs
patching sources
Run jailbreak-cabal to lift version restrictions on build inputs.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-Glob-0.7.10.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-Glob-0.7.10.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/p19ggmfm45zaaqm7q124y0kzhpisq29j-Glob-0.7.10 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-Glob-0.7.10.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/p19ggmfm45zaaqm7q124y0kzhpisq29j-Glob-0.7.10/lib/ghc-7.10.3/Glob-0.7.10 --enable-split-objs --disable-library-profiling --disable-executable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --disable-tests
Configuring Glob-0.7.10...
Setup: At least the following dependencies are missing:
semigroups ==0.18.*
builder for ‘/nix/store/4nw38gmfxp3wqwp88sgfkn2mhw0g9zqb-Glob-0.7.10.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/4lplkhrvrnqxa5q3xirl15qipacxfzmd-ghc-7.10.3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/4lplkhrvrnqxa5q3xirl15qipacxfzmd-ghc-7.10.3.drv’ failed
/home/david/.nix-profile/bin/nix-shell: failed to build all dependencies
```

It seems really bad that it's trying to build GHC, right?  It should just use a GHC from the binary cache.  Did you run `nix-shell` on the same commit and get a different result on your system?  That would be surprising.

Also, if I try to run `nix-shell` from commit https://github.com/DavidEGrayson/update-nix-fetchgit/commits/fcacacda23575dcdf2b2e1ec3fe0daec9509d091 , which includes most of your changes but no the nixpkgs pinning, then I just get the error from https://github.com/jwiegley/hnix/issues/39 again.  That issue in hnix has not been fixed, so I wouldn't expect our program to work in nixpkgs-unstable with the latest version of GHC.

**Comment by expipiplus1** [comment]
Yeah, I'd accept a PR which has this building on a stable version of nixpkgs. Until then I'll merge this one.

It's super weird that this doesn't build on your machine. In fact it seems to quite defeat the point of doing this. 

I can run `nix-shell` without issue here. 

I assume you can't run `nix-build -E '(import ./release.nix {}).ghc7103.x86_64-linux'` successfully.

What's the output of `nix-shell --pure -p haskell.packages.ghc7103.pretty-show --command ppsh < $(nix-instantiate -E '(import ./release.nix {}).ghc7103.x86_64-linux')` and how does it compare to this: https://gist.github.com/expipiplus1/02b2ca00ad65475652cc2541a6fb6250 ?

**Comment by DavidEGrayson** [comment]
Indeed, running `nix-build -E '(import ./release.nix {}).ghc7103.x86_64-linux'` on commit 1a62d35df9be78134b6973f3d2a76054eaa7bfef results in the same error about semigroups not being found.

The output from `nix-shell --pure -p haskell.packages.ghc7103.pretty-show --command ppsh < $(nix-instantiate -E '(import ./release.nix {}).ghc7103.x86_64-linux')` is here: https://gist.github.com/expipiplus1/02b2ca00ad65475652cc2541a6fb6250
  Compared to your output, it looks like almost all the hashes are different.  For example, your derivation uses `/nix/store/f5m5h3b4w3kma5k8i41dqydq6bx0y9ak-ghc-7.10.3.drv` while mine uses `/nix/store/zfb0v8brqpk8j930fbmhcjb444fj105z-ghc-7.10.3.drv` (which I can see was built successfully by looking in the Nix store).  In contrast, when I tried to just run `nix-shell` (see my earlier post) the derivation for GHC was `/nix/store/4lplkhrvrnqxa5q3xirl15qipacxfzmd-ghc-7.10.3.drv`, which does not exist on my computer.

Here is some info about my environment that might be important when comparing to yours:

```
$ echo $NIX_PATH
nixpkgs=/home/david/.nix-defexpr/channels/nixpkgs
$ cat /home/david/.nix-defexpr/channels/nixpkgs/svn-revision 
87131.292bfed
```

**Comment by expipiplus1** [comment]
Ah, I see what's wrong. I wasn't actually using the pinned version!

Fix on the way!

**Comment by DavidEGrayson** [comment]
Nice, commit db0100abda9dadba85c0f651ecb8480c344a69aa worked for me.

**Pull request merged**
